DROP DATABASE IF EXISTS DB_SEIXAS;
CREATE DATABASE DB_SEIXAS;

USE DB_SEIXAS;


CREATE TABLE CLIENTE(
IDCLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT
,NOME VARCHAR (255) NOT NULL,
,TELEFONE  VARCHAR(14) NOT NULL
,CPF VARCHAR (16) NOT NULL
M,DATANASCIMETO DATE NOT NULL
, VALOR DOUBLE NOT NULL
);

CREATE TABLE APOSTA (
  IDAPOSTA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
, DT_APOSTA DATE
, VALOR DOUBLE
, FOREIGN KEY IDCLIENTE (CLIENTE) REFERENCES CLIENTE (IDCLIENTE)	
);


